dist: xenial
language: python
python: 2.7
sudo: false
cache:
  pip: true
  directories:
    - eggs
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=5.0
    - python: "2.7"
      env: PLONE_VERSION=5.1
    - python: "2.7"
      env: PLONE_VERSION=5.2
    - python: "3.7"
      env: PLONE_VERSION=5.2
  fast_finish: true
before_install:
  - pip install -U pip
  - pip install --ignore-installed six
  - pip install -r https://github.com/plone/buildout.coredev/raw/$PLONE_VERSION/requirements.txt
install:
  - buildout -Nc test-$PLONE_VERSION.x.cfg -t 3 annotate
  - buildout -Nc test-$PLONE_VERSION.x.cfg -t 3
script:
  - bin/code-analysis
  - bin/test
# after_success:
#   - bin/createcoverage
#   - pip install coveralls
#   - coveralls
notifications:
  irc: irc.freenode.org#plone-testing
